server:
  port: 7001
eureka:
  instance:
    hostname: hmx7001.com
  client:
    register-with-eureka: false #是否注册自己
    fetch-registry: false #为false表示自己为注册中心
    service-url:
      defaultZone: http://hmx7002.com:7002/eureka/,http://hmx7003.com:7003/eureka/
