server:
  port: 9527
spring:
  application:
    name: springcloud-zuul
eureka:
  client:
    service-url:
      defaultZone: http://hmx7002.com:7002/eureka/,http://hmx7003.com:7003/eureka/
  instance:
    instance-id: zuul9527.com
    prefer-ip-address: true
info:
  app.name: hmx-springcloud
  company.name: www.hmx.com
zuul:
  routes:
    mydept.serviceId: springcloud-provider-dept
    mydept.path: /mydept/**
  ignored-services: springcloud-provider-dept
  #prefix: /hmx #前缀
